name: lateinit
description: Make easy for flutter build widgets.
version: 0.0.1
homepage: https://github.com/LateinitTN/lateinit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: SemiBold
      fonts:
        - asset: fonts/opensansb.ttf
    - family: Regular
      fonts:
        - asset: fonts/opensanregular.ttf
    - family: Bold
      fonts:
        - asset: fonts/opensanb.ttf
